
# META YAML

# Note: To use source:path: below, you must first
#       run dev/release/make-release-pkg.zsh
#       to create the exported source directory.

{% set name = "swift-t" %}
{% set version = "1.6.0" %}
{% set major = version.rpartition('.')[0] %}
{% set sha256 = 'f5b26bb1ac427c271e19dff2146101f7c4da03652d66426a291e96638ba15c03' %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  sha256: {{ sha256 }}

source:
  # url: https://swift-lang.github.io/{{ name }}-downloads/{{ major }}/{{ name }}-{{ version }}.tar.gz
  path: /tmp/distro/{{ name }}-{{ version }}/{{ name }}-{{ version }}
  patches:
    - swift-t-settings.sh.template.patch

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - ant
    - autoconf
    - clang-14                  # 14.0.6
    - make
    - java-jdk=8.0.92  #                       1    bioconda/label/cf201901
    - openmpi-mpicc  #           4.0.2
    - python
    - swig

  run:
    - openmpi-mpicc
    - java-jdk=8.0.92
    - python
    - zsh

test:
  commands:
    - swift-t -h
    - swift-t -v
# - false

about:
  home: http://swift-lang.org/Swift-T
  license: Apache License 2.0
  summary: Swift/T - High Performance Parallel Scripting Language

extra:
  recipe-maintainers:
    - mrakitin
